global:
    secrets:
        k8sSecretCreator:
            apiToken: ENC[AES256_GCM,data:oUhU2n6G1KF+rTS4y5PClGNNUY76kxoLRAT9uDui5QU=,iv:NrEJpUz9+W0Z6K26gcX4Hg5HXNz+z4Y3bqlHHDvYGgM=,tag:WubR1EqWy2xfgEfMCPNaTg==,type:str]
        keycloak:
            adminPassword: ENC[AES256_GCM,data:3+4+yGKoFZV4eMe5n3pt//NGWySlF24KxCzr3Ps0Fyw=,iv:JjwyYXBQAYV6PpELRtDdioTm0U6/O8fPjHpukKIyDBo=,tag:O4KxjtP+urHf8VV8CjlTIQ==,type:str]
            naavreClientSecret: ENC[AES256_GCM,data:3VfUE0ZjLNGFxF8b4/JaOswG8/gmF15EvVpjdc5BFqk=,iv:oepEz3KKNsgGqqO0XQYVFH+lJ1VRNG5iHttx/VHNgmU=,tag:5oKperELYQkKN3zy4EKQ+w==,type:str]
            #ENC[AES256_GCM,data:ADNjhKxxZccmzgTDi1vzfF9lLImcokSmiJTZ5itzScqr8FZouUFBG40OXVTjLT1CBYySENW2BnRjzk4zcjuI/PxRy8SfYG8=,iv:SPmiWY0Mj819s+/AWNEt0vMzNv3CCKKER44EVutDPmk=,tag:KF589Fiq+SZJOXCt9nR9rg==,type:comment]
            users:
                - username: ENC[AES256_GCM,data:1B34Q03xIQ==,iv:bfgPd2+BT+kUz9jBW5YkGKbq6vB8FPxwmbfzvIeaVrQ=,tag:9Bz6ng22fW4m5+47ns1v6Q==,type:str]
                  password: ENC[AES256_GCM,data:8Ckuixk2MA3qTO8BCDrljRdqkIaJnYOfeBPdC39pcs0=,iv:OmCsXRbWJR4Q3Xx70ESZYwnHTH+ldUXQ3iWUW5jcFko=,tag:IfC3u7mmil7w1eBOo2SiZA==,type:str]
                - username: ENC[AES256_GCM,data:ED6YnQ==,iv:tmQxFV0VVkbXv/fh4xkH/OtChvOmYlm/shvqnLiqGdE=,tag:zeCkFgX9Vsa+L/EKPtvueA==,type:str]
                  password: ENC[AES256_GCM,data:aSayj+MWz0vq/la8nKhL2nI4BLjcJEEubV2ylKSrbIo=,iv:WIe+UVDVguUkrjqp4MueQjAwd7FfRwnzIxynqph/OhM=,tag:vblablJa6jhJ737VX7AW1w==,type:str]
                - username: ENC[AES256_GCM,data:vbTNbZ17,iv:CSQcSh4AvB9diyGk6xo5kMDp2rnTFD9HuSnc4DS3DsA=,tag:V+40FAyYR93gbVIXcGHsKw==,type:str]
                  password: ENC[AES256_GCM,data:fCtFZkL7CGN37eoWAXjRAUWFeEOxnSYZCOIvb/cPaT0=,iv:ZoPrAqLjMwWN585vLILIEKklX4yiSWl49EMg7u7oKYU=,tag:TI05qK1aQr+RzmE9UAavUQ==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:aYA1A9qdQZ/71b22QNaUNGzGGA6CFavOUar38hZz4LM=,iv:d1F2Dem33D1PhRKdGFZ8/qzkJAYDMqGuJtRADY+8YbU=,tag:Pli/72g02KhGsTFrbg4ceA==,type:str]
        naavreCatalogueService:
            secretKey: ENC[AES256_GCM,data:OHw4d6HufJDYoEeIo1PafEeazXkM908zsEmLrJheYfA=,iv:yVwib72zqQK8S4lahslEDQDvkygZig3NI60DaypGqyw=,tag:Jp3oFw3FsqNqTEuSdKqAhA==,type:str]
            auth:
                superuser:
                    email: ENC[AES256_GCM,data:CmmoIu7iTfMibyanv+Con/g=,iv:ARszOvVEg9XrYCiX38q7Z3Up0klHU5nkI95VvlP8rAA=,tag:iGu2L1X7F/NZSXVPYREm3g==,type:str]
                    username: ENC[AES256_GCM,data:x9+Bne4=,iv:vM6YbhBslTtMfSCHUe6h7/EOxNhJAQesjSohiGqJqT8=,tag:2N+nQLg3pzt3m3KnZw7bRg==,type:str]
                    password: ENC[AES256_GCM,data:oDnPZcTzlfrDBum2NIsUiXHObX798jIRbVSvqfWrQNg=,iv:uqgU43bypjbuM8bsnXrD/nBqol5XknvzmPb8qp3t7d0=,tag:td1qii8X69JHg4Biekni6w==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:5JSo1+n98KjGrrJI4FxGayN00QQ7pVsFC6sIpTvCb54=,iv:f9tkRkyVTjxhaPwetLzL/E9OOPQt/TnLZJG4+wIa6Ds=,tag:YHrmjDMpWuo20WVJqzas5w==,type:str]
        naavrePaasFrontend:
            secretKey: ENC[AES256_GCM,data:LUvYs8a9Xl8saS4sbXJUAnwJL0SVpz2Hj9DyJORF9eI=,iv:7OgSi4xGLJX+v1Akf34tyl0/B0ESUtYNEGiay/Cyj/E=,tag:cyHzAnO2Y26uha6YLuow1w==,type:str]
jupyterhub:
    vlabs:
        openlab:
            #ENC[AES256_GCM,data:ANRW/bsnHD8EY+qne49lW61NAJzWe3vjXJdEFforl/r+dcuwDFE8ZLBwEh2ksomk0bvaDGkJZddbihROqerAYjCQWxtM,iv:oqpie5KeOwHC65cnlu5RKfw2JcQpaegtaMDyRJXR6Xk=,tag:FJhUvhe3hK6czSRfAffDxA==,type:comment]
            configuration:
                cell_github_token: ENC[AES256_GCM,data:8/fQbGEJzdzKLBsbziigbDjpUSsezpunipd4Frf4Uczu2+rwsqCwqH3tikLnXgqG/ePlMfdeASO27RwydOKa6rsoKvauEQ+7Ujp+ofmaq0nvBkdmLWVopWxusZ2w,iv:xnAMaSiw+a4AhO7XJZL9u4neaoey5PU5KzS3a+vqxnM=,tag:kDKCbmTchgHYl8VPilJGUA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-04-01T09:37:52Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEU/807HLY42unOGgu9ryLKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0mqrO7yoqcA+A0BEAgEQgDt2t/l/+X0pMrV+7xOUJ6fHXQBrJHDHUkM+Nn3FxxRYCJQKq7Vcf5vqwx+12z/DhezPBQgGHIyp1EFJEQ==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-04-01T09:37:52Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQHCYFNAC0M5Kzm2MB9/KH2KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdmtRDANIK0lu29C/AgEQgDvkdYSv1hP6fQcoLH+WdM/nqIbUl60YsLi4rGuDoCTH8NFrNclJq765cUc0cRvg1Y/3JgVR9uNHq+vD9g==
          aws_profile: ""
    lastmodified: "2025-06-09T10:47:30Z"
    mac: ENC[AES256_GCM,data:6NzYzH72SKHyaRGfQ44PTOidmqlKbpP67JPG6sUkIE1sHcz2pajxyv9wGuQbuBOAJSpfug5KEb/CjM6hT4oPcrevtveTeRdVG1BfbBmBp/bKdNvP2CYfmO1+v1/tLsWNRxTMaTSQDn4kDxT3jf82/7dE5KksbyxAEZ2saTm8enY=,iv:O5NYDuAfX2b+yh/YxPrtaDsHADPDUXUDzalgOyhqCV0=,tag:0LCcdyfGlTlyJcU2MeTDEw==,type:str]
    pgp:
        - created_at: "2025-04-01T09:37:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAI/bkG6aLNKhZ+dMYquaTT5gijCXi0vBEoD8RRlCBqQcw
            nlQr4KjfPtRY1ZX95z+eVJT0yepAZW7JoGbFHgThQONZ7wm0te+x0KVlDjOn9SeI
            1GgBCQIQMymTP3TI3COWKwRlONWKWk69Ok9ABlF3rUiHXl2tua+xe5mXfvA1JFHh
            ubn5IEPBxw0ycLunQ2Ztb818ie7o/FM3du5z5XVnngqjgdS2AeKW5EoLt4nVd2jP
            Ex8LuzGeFXp95g==
            =NX02
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
