#ENC[AES256_GCM,data:G3D6vLi0PrxtXWgNgq39IUA2z4tl+mgMmtzG8O0pBtttLuc+JFOeohaM2ewfLrqn+RcQ5erIJDzEBlft,iv:C9ErqitcnRMJmtu+5z19zMsFUAuxkNl+qGTes3yBsIY=,tag:bpcxW9gktb7fo6piSLRpCA==,type:comment]
#ENC[AES256_GCM,data:6w24sa00B1KNGrUbFcmKGPikGOVUw2syZ3M/YqX3dqeaYD5Arp3TPY8zRgQzVgNcg2qJYOxMYKOZKx1lR8cx8nE30ZCBthnFt2j/w4iI+x/JSJ2k4Jv6ecVxiqOLcKgd,iv:RUDWIwpTwY171sfFAZWNAf1njRgKx4kecfn+uf6RLpY=,tag:pJNTx7ss+YPzzl+lzJbdNQ==,type:comment]
#ENC[AES256_GCM,data:JjrBnmIBchUn/ixfXp6swcIcOD6Zm59XfH5DZ43q8ukAVrwqcyLyc7RJDqk=,iv:M+3d1IecrWcalk85na1B/fRk5naBgRrfMDfLCJFa/04=,tag:Y4GBmwShv4Udks+JcxkmYA==,type:comment]
#ENC[AES256_GCM,data:U2X0eWh/EwNIL/GKPtckuBRIzXqUNUC7Y0A/iXUKg2tqeR3seeJuA0PLKUDJgZ+8vlTthVLwxUECe5k0+5p/qKtr3gl4G482aOpo35RJ/A5+8VMKG+DooXUxbA==,iv:nRr7SnwpZJh13XAxvDfeJ/E7uja/64tGWFfOCFW1XcA=,tag:NaCzZW+n7BfnWpiO3ZjryA==,type:comment]
#ENC[AES256_GCM,data:hib/CTduha2f8Mu2J+23iEi+MXkQnioIAV/apPYaLLmEMCK9w1XRN1Bt8t99ovBSS05oI8Dhqu1+x95dSkvDP1/mi1UVdXFF9VR9bnUrbYA=,iv:9po2Hnlb2zVqfxiEJ4p9y0bK3mGjLDc8T6gFEsNtwPs=,tag:y1sf/e5nSRYCO0lxBOUvEA==,type:comment]
global:
    namespace: ENC[AES256_GCM,data:h8yNJcgKh5t2sw==,iv:171FAAk114aEGC2qjAcOcj3HpSaNb/4qBjtxzfc+dyc=,tag:z6xGCJWUg1WzcUrD82dJTA==,type:str]
    #ENC[AES256_GCM,data:hOO1KmedgolhwqH74AQ9WyYGUjUMdw4JiQhyEii0SYoakPA53NuXlT4X8C8cfLnD4Wrc7nRWnZ7V/A19a6jvSmwn,iv:M4Lm2js+iFyl/FZailtEZNbeaCHhQQw3T/+egoLcix4=,tag:H//poox+X6rmxC3HWDm6QQ==,type:comment]
    insecureSkipVerifySSL: ENC[AES256_GCM,data:cgU3DQ==,iv:fO3R5Yko5/rxgA1aC3k2v6W05SWJzwrTa9tj6w042rY=,tag:X366Y8Yb0OXS6lZ2L88Q0A==,type:bool]
    ingress:
        domain: ENC[AES256_GCM,data:FBuppcdgmWwBQjIUv8AHiMTywZA07kK+,iv:MCN//HSP8LS7Xk6y4Q/WRudXJ5QjZVqwEdP1X0+mv14=,tag:5McGBfySjPy/Q8Modc8mAA==,type:str]
        redirectDomainToPaasFrontend: ENC[AES256_GCM,data:Ep7Lxw==,iv:Py6F/ezM/A3Eieiy2la3f0tWod5rVDJ4dJhhvpMPiQQ=,tag:SNosTLfdtQCnZFyPeoaLag==,type:bool]
    secrets:
        k8sSecretCreator:
            apiToken: ENC[AES256_GCM,data:R+AaVNTMbm6dgpBRuGXMrKwzNqM3Uucuwm5ZeXr4,iv:E9VZrdTeNXZbtRkxV0o9NYlIJnPQdO7sMvfXnG7REts=,tag:eZq/jqiwth1YMfOFRSYubg==,type:str]
        keycloak:
            adminPassword: ENC[AES256_GCM,data:Ak23Svw=,iv:aje/KDX1AlNjPGBntnPVc7TbPQ/SbkVm28tLGMuAuDA=,tag:aNAYol/onShKQ0P61IpnuA==,type:str]
            naavreClientSecret: ENC[AES256_GCM,data:rFrUF1qbvU5Y3T6XnE6jkXqlsWfHRz2pGOKwkxxdXUE=,iv:AWcXkgK1Ysmv+J+jF0XMauy6fzD2sDCjtBAmfNUYe28=,tag:SOVa6TpAHrxV78bxm3QoqQ==,type:str]
            users:
                - username: ENC[AES256_GCM,data:JI4eNQ==,iv:IoSe+EfpCeNTeyovj42wtq5kLlAFJMwZlO9ZDceyqNo=,tag:PrgPwTMNn4F0uv0SRD5iOA==,type:str]
                  password: ENC[AES256_GCM,data:WSwd2g==,iv:GCbLnbynNBBC62aVhseD7hz6mhmqccFlP+s6+W9Ln/w=,tag:DA7kwt9+/o5w45RXUFnfYA==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:F1vQAfC43AnIvmZUeSV6z5KuVZZbRNKqpCTspbbeEYmw,iv:kfWHaObYXxFIeD69lGMcaC8jFVySIk2nhvfe/5EA7cs=,tag:YDfMPS7kZr7MJvgQrdnTYg==,type:str]
        naavreCatalogueService:
            secretKey: ENC[AES256_GCM,data:VzoJkNiD1IH9IWHPPbKMylyRQoB7awDeDZIDvFXKB4R6wOFFug==,iv:tGpG/bxOIejkEluqdflnmUMS1mVhA6Rv8KCVJ8hsV6w=,tag:gun+BRgtOgaPpij2MAPZOg==,type:str]
            auth:
                superuser:
                    email: ENC[AES256_GCM,data:RZFk303kuDBYBN5ASrFR+IU=,iv:iJ/4SLbTId2h23xEl+0g9zR2XqBFVyT7cD0zHrabPOE=,tag:3NoKkE4weDHkiVOyp27Bsg==,type:str]
                    username: ENC[AES256_GCM,data:otOvb6M=,iv:mC1G/0dnr0NcDQaq1GZl1HtctvGL63dWzqrp1C5/boA=,tag:NncanNPyPZor9Bn1txgwSw==,type:str]
                    password: ENC[AES256_GCM,data:QIIHjqM=,iv:E3d6hOpp05LpTa9Et9gSS0TqEXgoI8W+OkA9ZatOLgM=,tag:wi0vc8HJmbSJD6g+EvxaCw==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:RajZRmmrgnWAyO81qcfUMcgEwb/DZSovHRLc0nH9j4X0GwfBm8MnAOaySwZVj9I=,iv:p8aiJUH77Au4FkAwMDrmut9DNyXXlaDqlUU/WId4jag=,tag:VxTQdaxCEE8CUYppR9Pzqg==,type:str]
        naavrePaasFrontend:
            secretKey: ENC[AES256_GCM,data:/KHZKH53BwzGXwzYcc1QvSLUgFp/N9xVNC+juX/DtpGv,iv:JFSHM030lUqp+XVzotF4lbsM9+OGz/rbfSTVAZtw7n0=,tag:kHQbvabN0wGwMtgA7ijfvw==,type:str]
jupyterhub:
    vlabLabels:
        sampleLabel:
            title: ENC[AES256_GCM,data:JaI6pX4IDIfJE6FQ,iv:0MluDDgFQ5ZSaO87d0krPByPy0JZPAbqL7VfIr9uEIc=,tag:HFnQJ1cbUx/SwyZ9l+OpqQ==,type:str]
            color: ENC[AES256_GCM,data:QA0OretdEw==,iv:F5dohrfZB3Pg7DhJXje0QFyvu2WJCd80r1pBBOS5o4c=,tag:LfrWd2Gv5j/9RDIO0CR4hQ==,type:str]
    vlabs:
        openlab:
            enabled: ENC[AES256_GCM,data:EO2tQQ==,iv:ILZuy1qcvVeQBnAfx0Dv3xaPK1aUANH8Ay69wmE/8+w=,tag:BCLIkLCgc6J9RmPsGyWizA==,type:bool]
            slug: ENC[AES256_GCM,data:lopl/Qgk3g==,iv:i7FYsNqGykLkDM/77+RIhggJHnPE9nfRH2rwCDf8cFw=,tag:FbarhkDt4M6soDMvoi4rHA==,type:str]
            title: ENC[AES256_GCM,data:3BPpUUX8NUtiw/e9sRLe,iv:zvkBpThJeGzX8w8aKBl33OiZq70XLP2y+rxadHWIYYs=,tag:GjPSHC8nyJIVcglONrzJTg==,type:str]
            labels:
                - ENC[AES256_GCM,data:T/NgAPdwovxaIQI=,iv:nQCTeikuMi1LBbouXuBG+fm+z5qMJuphLXWQDsE9fg0=,tag:Di+6fmGWp07SqbJFWsIAnQ==,type:str]
            description: ENC[AES256_GCM,data:EU0kyMilGmXT2Z34xYxKbnwIGG7pgmT4s7acvulOPdynHbqxiW0=,iv:SRLbGjjIwpAv+zGyCd62N81NoNkxdGKWimdvETdgmdg=,tag:mTTuF4yI9q/GLJpaOZXFvw==,type:str]
            dirname: ENC[AES256_GCM,data:nzLfVSW/nbI=,iv:WrZoXj1lg2srX97zC4f3y+ulrYencUwqAHRpMw6nmkU=,tag:7vB7vhw+qGWUmYKGHhz4Ew==,type:str]
            image:
                name: ENC[AES256_GCM,data:jtu7xOhHoaovqDxLfOHXRx5vk2xmwyaomLLF8TiAUoum4mVD/kNQ0zaCgs5x75Yo,iv:5u6mkHiptiDSUTqRuWsHxFKBqlfrRXjkFU0OkZ3VT1E=,tag:+znp+e9JQrz5nw/04ackYw==,type:str]
                tag: ENC[AES256_GCM,data:xzOR63znHw==,iv:T093go2CZvLuLOhF2d480svPE9UW5QSWDIWdT6Gc/Tc=,tag:H8oXLPtTd/Sga8oqJ+vKYg==,type:str]
            configuration:
                base_image_tags_url: ENC[AES256_GCM,data:gdJWX7sqprVBzrzIKVE0G/nITx+p+zOtx8NZr/4POX5YH4RNgRZ5JUvpgEec8HWgp++0e4hGKu3I67G3flRVqW5/P3oXN2/thDqnuUMuNzA=,iv:AObnbCzd3LH0oPuu/nLS6LmXKFHCS6u3fm8FSFEuA/4=,tag:NeSKoLlb+Ru/H2yx3kxj8A==,type:str]
                module_mapping_url: ENC[AES256_GCM,data:fp57oN5XHRLp+tMQhBcQJXOdNV3n1oDlgLAp3mP9lQJyW+epd/blTw2/cbt0qdEPDVDcAR7N+Hv1YZZN3LoLalhf4YowDBggA6E/gA==,iv:LKyZOMsBR41amBcg26aqobGIispE3He7L41ShA0hkVM=,tag:u6vZWVQr0ufaOqvHz6hIbw==,type:str]
                log_queries: ENC[AES256_GCM,data:Wh+KCA==,iv:zxFDV8OOt5TXp2bwnkhnmYAWjgiwRhXfNQS95fr2MD4=,tag:/wGliDWIpVpTxyCPFtkYFA==,type:bool]
                #ENC[AES256_GCM,data:HF2i1dw0qqS6viNab7NFb+mBtdWR5uBA/9EFZfBzJTL1k4tbE+OSY/W0OXzh6Gr28yG4/WIJ6keYyaJFI8CAmZ1Mfr1RZ2r+ZCEIRNmBlRYss3Us0wC3tYI=,iv:egoVWAFT69mef6omMfK+6aDLXQCvTIDrjzm8hQvedXo=,tag:CNWaRBxLurWWNQRmVVgUSg==,type:comment]
                #ENC[AES256_GCM,data:upKRYq+vTTkg5EKeDB+jdcHmV/2KPpn/CnAURaSMJT8vi5ySWNFIGF+Rke0zKGwBgUiTjWlCPtcj/xT7WKavxw11JWeQnLsWxvgqzCyCRrUJcl3dluosGJ9J,iv:aWkoxUrpQPKmIRVzI2aBFU7qiFfSHETMNhK+soMiZGA=,tag:Bv1RyijxgzuDrhbIj/hE8w==,type:comment]
                #ENC[AES256_GCM,data:JnRIGbSNT3sxpbkT+mFYG7HtuIQcURr5F4xxOmpvsfHZnfgX/qo+n9hqJxJkbYrZkovnoWQQTUpxNYnDWJ/F24A82WjURyT2dodT1Bg+2H0c63EqYg==,iv:eww+tJuCPc7rpsaW/rwyEBaY+EETL1RC0lw+SbK5/dw=,tag:+HvWNvJ4Re6Bwu0W9AXcEg==,type:comment]
                #ENC[AES256_GCM,data:mDyHIAtyfowiSY713JZOtpeqNw==,iv:BCdvVK2MfgPFBmnzqkJnKjw30QbR+Ii8N6AjQRm3Dcw=,tag:5z5Mkp3TkF2XvHcWRUrn7g==,type:comment]
                cell_github_url: ENC[AES256_GCM,data:LkzjYKUXwyAF8KkkVGVafG4i7jLCsVFfXl+oug==,iv:UtWHyOpMfkYO5lDsDW8Ci7hxEc8VldQ0sMPQ11U7r7w=,tag:ApZo6Zh043Auypa9BOGvhg==,type:str]
                cell_github_token: ENC[AES256_GCM,data:GgNSq75L/Gt456+vHbfSXytytoBL6Q==,iv:hN98PU8Vk584xviVElYXUHkm1HMmgjBpu/IPHjgF7I4=,tag:d9Lhtkx8Aj8idq+07B9tCA==,type:str]
                registry_url: ENC[AES256_GCM,data:EXcujYMbEzj6ouW6NrOyT8Y=,iv:25GhAiiz75im5hUbjHCwdlXlNVQiAdLd4FqdHr8H9G4=,tag:3L/9LMLXZIQj8LYK84OctQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-11-19T10:20:23Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwG0/oIuW5zgADzUnFTv8wwGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpUD8UFbu62P4TsZPAgEQgDvoKPKD0y1lCScds30IqMjIYMCHcH/A2Ka+SeyV0fJ6C9UmB+pcee70ZNKTy7PrGwhsuRP6w5HZCZfdHg==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-11-19T10:20:23Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQHKIIV1gppwQBz/tE1VFhVKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3YEDSlA2x3RtoqDXAgEQgDvNEtifdVRMPAv2KwQONqBZ24kLdUC7OtaYcqU+UrL2IkXTdeqWoSZTjnuVhKq49h3qInFRqk7pvaiGKg==
          aws_profile: ""
    lastmodified: "2025-11-19T10:20:44Z"
    mac: ENC[AES256_GCM,data:Ab5bAzNaCS07uTYqSpvp44lsa7wD2S9L738QrebFyHSVZOhYSglxLpgRUH9nXIFAf0+Lsk9yliKUptS8bJjrHiZgETGb5139zpHyCe1NkVwFr/P8FnXWF3h5M96dav+LaersxTxJRyHDTw/YnndurCVqMFGT8/ul9xzCheUoZ30=,iv:O6MCrDlx7KhDggmZiHB2TWtqsop3sSAk1oLvD/2XlYI=,tag:BleYbJDsWsaz5kxJ6vsddA==,type:str]
    pgp:
        - created_at: "2025-11-19T10:20:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAX51jCHuN478Ozw73IOpQyXsOZmY+6m3Prg7jjH5RG2Aw
            j+T2/uqXejGcUOzaLoNVEhrH8t7t4Q5pDmf1lk99xGgRIi485guW+zFaZgfOPsAz
            1FsBCQIQ4aZfpb3lBCAjaXOkT4r9dGADqndpr1wE+1xXwUOn3JbuKQuyEqLYrJ2B
            4NjUVk4os0uVz30IH5JsvANTvHZqQ8c2GJSXfTHoJL86fjtCXeM7DLEXe50j
            =jcOf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
