jupyterhub:
  vlabs:
    veluwe-proto-dt:
      enabled: false
      slug: veluwe-proto-dt
      title:  Veluwe proto DT
      description:  Veluwe Digital Twin prototype for LTER-LIFE
      dirname: Veluwe proto DT
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-lter-life-veluwe-jupyter
        tag: v0.0.17
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.0.17/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-veluwe-proto-dt
        registry_url: ghcr.io/naavre/cells-vl-veluwe-proto-dt
        log_queries: true