jupyterhub:
    vlabs:
        biodt-hackathon25:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:UOZSFfAFZ9Zq4m0Xrbog1xSY6PdLGeZpDv8ojia0ZILta3x5fr6SV+S9LkHHrc3xvKN+cq/coGCVDzCyySHEugUdFdaMVBoOBGGES+ot4KhIWdyDcOnISzJ5kTM1,iv:Lr98lv15ymA37RV19x+H/Jhk4Pn5WKmturkGFPWwo9M=,tag:hJYMeBz3g1RLtjrt06+HIQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
          aws_profile: ""
    lastmodified: "2025-06-09T11:56:06Z"
    mac: ENC[AES256_GCM,data:fx0AXljhRQpoBu2mm1EFi5YPyq6ezOjWa1SYFHnxeXRLV2KtICy24v4JNJnH99GsG8JhbDSnTdmEpUpUlNAXyvOLjWy4NpVDWfkDYiwpyFtBiLH7XR6fs+149phS1HM/HIUPDcfCqKQTLEroYjq7vTfzr4Bs3sN8/zlkd1TMZ3c=,iv:PzOnK5uBu8gBv+FTUO4twAT1Tw1lhuMBH87GbiN9+5I=,tag:+ydCScKhcgMH1iF+4340WA==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
