jupyterhub:
    vlabs:
        wiresits:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:DTBvgdyeuMAkePZDa/tW8WKn/SdrUPwhLaMhIs6nkh39C/3rRHKv+OXSSVjp5Y5F5hTlL5vzRbiLcPX6sn5Rwb1ELVY9/v5Jnb/A/S2CsSUp4K2TqfIl9lR9/CPh,iv:Bw5kXjmpc11e/fZJpnZSMwUoeIJmazU+IEKF1pNLQf0=,tag:YK2h0l1k41wk0uSzfnimsA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
          aws_profile: ""
    lastmodified: "2025-07-16T15:01:30Z"
    mac: ENC[AES256_GCM,data:odyGz1fb3oNykFzs2x1a/deBIPaeL+uq52Okq65OZD0Olgmh9DIsDHdAalF18v9Ex74DR8Qx2mMo9f6o9OzZ33ri64+I3MNLQdAC5MXHCW7NAgYdRSS+X7/LpoUgCrZ8pn+5snelv/fjog+kbICof5sXsvmATy/jdZjN2MabxOs=,iv:vhjt4R0Qao6FxEptBbi6v8yfbDjuYPplESnBh8K9zKQ=,tag:5EM860Q9Uqn79buw37JN4A==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
