jupyterhub:
  vlabs:
    veluwe-forest-model:
      enabled: false
      slug: veluwe-forest-model
      title: Veluwe forest model
      description: Forest landscape modeling of the Veluwe
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-veluwe-forest-model-jupyter
        tag: v0.0.11
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.0.11/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-veluwe-forest-model
        registry_url: ghcr.io/naavre/cells-vl-veluwe-forest-model
        log_queries: true
      postStartShSnippet: |
        echo '{"CondaKernelSpecManager": {"env_filter": "/opt/conda$", "conda_only": true}}' > /home/jovyan/.jupyter/jupyter_config.json
