jupyterhub:
  vlabs:
    veluwe-wolf-deer-tree:
      enabled: false
      slug: veluwe-wolf-deer-tree
      title:  Veluwe wolf-deer-tree
      description:  Wolf-deer-tree trophic cascade in the Veluwe
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-vanilla-jupyter
        tag: v0.0.13
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.0.13/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-veluwe-wolf-deer-tree
        registry_url: ghcr.io/naavre/cells-vl-veluwe-wolf-deer-tree
        log_queries: true
      postStartShSnippet: |
        echo '{"CondaKernelSpecManager": {"env_filter": "/opt/conda$", "conda_only": true}}' > /home/jovyan/.jupyter/jupyter_config.json