jupyterhub:
    vlabs:
        veluwe-forest-model:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:O6KnXmwJqJMfG1T00Ru+w6hadeZAOacIyxaxmN7xAEfKfxqGllv567yJI2rd2+6enx5O4OCDBTnv2h7WzPcsPHM+sLy05rk7TTrMCebGb7gOVdNiJRx5dyhyXO2u,iv:j+9X/Ah5810ahkQ5kujfDJf3UyyTwC1ZAccaCDSNKSs=,tag:aE6xs/81Fqt+u2T8gWIEgg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-10T11:13:20Z"
    mac: ENC[AES256_GCM,data:snRfeMvEQZx0gLWjs4Oq6m4+fN8xWE9aCcOdL74uFkTzmcOZ28H5yUZGVbv+I2apCw6ayfYydTaE2dQkuzf0Q/vkDM4hBer7jD0ZsQhJE4MOhVpOo27hnDNyTpGO8IsCsDjdQyIK9ThXx6qwo2VS6b/tE75JmHd+lSM41rK22OU=,iv:fE97DlG12s8sqYh8qmFXIhfArcJ7CkA6mgkGIB0xBNg=,tag:tN/i/kljV8tsHYnvcRLrNw==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
