jupyterhub:
    vlabs:
        aneris:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:zFqH8D3BpRfW8YguaNGJtSQi2tBD9UD6Q718+SRvbF6qYCsl9mrNYliW9FbZtVKg/NyFodGSIuaEr5niOBwiJ3zr51Hc9qfNE+z7CMXW9Cd6M0QxfvuYq8vmXEF5,iv:oTPzYEMGxTC57jqiDu8V3qWlQpMFXFaRYcCBXOVhJG0=,tag:D0END5n1rugN2Yze9rN9Og==,type:str]
