jupyterhub:
  vlabs:
    homeros-seismology:
      enabled: false
      slug: homeros-seismology
      title:  Homeros Seismology Virtual Lab
      communities: [naavre]
      labels: []
      description: Creating and visualizing earthquake catalogs using machine-learning tools and algorithms for small (or larger) datasets.
      # TODO: add environment to repo
      binder_ref: gh/NaaVRE/vl-homeros-seismology/main
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.3.5/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-homeros-seismology
        registry_url: ghcr.io/naavre/cells-vl-homeros-seismology
        splitter_max_branches: 32
        default_file_path: README.md
