jupyterhub:
    vlabs:
        ecvs:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:rZRxU3vBfIhCCXIugfFBpZy70EhHRdO6Uc3yJvSMT+nK5/iQRX7otGckpNqTpxQKC5GMybhL7DWJlrKa4dayv1M6BcPxvkQPDHiG+idO9rI87W2ZBXMQPq9tg/tp,iv:3ANraesSJnC/0QO8SYfk2QBu2nFK/PwWfbfJzOLPcYw=,tag:nvHbOsoFJpdywkXNgcsIZg==,type:str]
