jupyterhub:
  vlabs:
    laserfarm:
      enabled: false
      slug: laserfarm
      title: Laserfarm collaborative virtual labs
      description: LiDAR point cloud analysis for macro-ecology
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-laserfarm-jupyter
        tag: v0.0.9
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.0.9/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-laserfarm
        registry_url: ghcr.io/naavre/cells-vl-laserfarm
        log_queries: true
      postStartShSnippet: |
        echo '{"CondaKernelSpecManager": {"env_filter": "/opt/conda$", "conda_only": true}}' > /home/jovyan/.jupyter/jupyter_config.json
        vl_dir="Laserfarm/"
        mkdir -p "$vl_dir"
        cd "$vl_dir"
        gitpuller https://github.com/NaaVRE/vl-laserfarm.git main "Git public"
