jupyterhub:
    vlabs:
        dajs:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:XsXApcdephDGE9+PNTOUSpr3Zy0OpdGiYXwY+ppT67RspE82BKiWdsbpz1+BzeNmT8Tkq+u7cDmncA+IC6NwFd1R/Qrv5bmQ9C2YSmk6r2cItAhBVdHLNTYKXhEb,iv:4MeSq9I24uImbDhio9Nh/eghwXGHmP9Pim3cntjHh+Y=,tag:p35QnMNTWS4ozn3YTIiOyg==,type:str]
                git_public:
                    repo: ENC[AES256_GCM,data:syEf6f3H/1DJLjrlsyT7YHTEYsQX5GJcxth7fCnwYi9BvrBM0cs6hm1ynLCsr+xA8zREAUqnR2iu0y2CVesgYp72Y5DGLSq+vliEdkjnxvF3I3ZXmZb9DOJ8Dyg7Q8rRukRExAtR498NdRLVU1PHDsTfl6MmwJZIXHzjowhjC+x5ZrAhA4x2iVAIcgPD9q7h6NqN,iv:cjKrr1XbKyAVnz2jCUgS1bb+OCMElwd08EE9wE9I5DI=,tag:s2KcQSMR7iOKG/gb+WQ9tg==,type:str]
                    branch: ENC[AES256_GCM,data:TU0FxQ==,iv:G5mAp6AQ3wrJgRI8eX9GvphUpUMpzwDwpqLl94Te620=,tag:4e/vVBLOv1ZRRXGc8Zs5/g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          aws_profile: ""
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          aws_profile: ""
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
    lastmodified: "2026-06-08T10:57:05Z"
    mac: ENC[AES256_GCM,data:/sfLnYF4DozPiRcZBEdGGDyuFKXT0nqUZ3uceUxCvucARYPgWQ/cOGeMnaMlQ1lvenkLeEpypm+mvyrUDw8BE3RdRLMP7PQ5HKnPTeHYrJCi0GPmjcv7FMKFOANHRdDbtOo6rSaxXidk2IkQfuvPbt7mBExjbiIUVQCYab7wVAk=,iv:S2qS3W0jytwjMTqGfhGZSwAXN347eHqQJS5B+dfXsX0=,tag:RBrns7F62sARUcbIsq4Qhw==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.13.1
