jupyterhub:
  vlabs:
    blue-carbon:
      enabled: false
      slug: blue-carbon
      title:  Seagrass carbon stock model Virtual Lab
      communities: [naavre]
      labels: [tutorial, marco-bolo]
      description: |
        A virtual lab to compile estimates of blue carbon storage by using essential variables and 
        satellite remote sensing at regional scales within European coastal systems .
      # TODO: add environment to repo
      binder_ref: gh/QCDIS/Seagrass_carbon_stock_model/main
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.3.6/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-blue-carbon
        registry_url: ghcr.io/naavre/cells-vl-blue-carbon
        splitter_max_branches: 32
        default_file_path: README.md
