jupyterhub:
  vlabs:
    veluwe-proto-dt:
      enabled: false
      slug: veluwe-proto-dt
      title:  Veluwe proto DT
      communities: [naavre, lter-life]
      labels: [lter-life]
      description:  Veluwe Digital Twin prototype for LTER-LIFE
      # TODO: add environment to repo
      binder_ref: gh/LTER-LIFE/vl-VeluweProtoDT/main
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.3.6/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-veluwe-proto-dt
        registry_url: ghcr.io/naavre/cells-vl-veluwe-proto-dt
        splitter_max_branches: 32
        default_file_path: README.md
