{{- if index .Values "argo-workflows" "enabled" }}
{{- range $index, $vlab := .Values.global.vlabs }}
{{- if $vlab.configuration.registry_token }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "naavre.fullname" $ }}-image-pull-secret-{{ $vlab.slug }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >
    {{ $vlab.configuration.registry_token
       | b64enc
       | printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}"
       | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}