{{- if index .Values "argo-workflows" "enabled" }}
{{- range $index, $vlab := .Values.global.vlabs }}
{{- if $vlab.configuration.registry_token }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "naavre.fullname" $ }}-image-pull-secret-{{ $vlab.slug }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >
    {{ $vlab.configuration.registry_token
       | b64enc
       | printf "{\"auths\":{\"ghcr.io\":{\"auth\":\"%s\"}}}"
       | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
{{- if index .Values "naavre-environment-service" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "naavre.fullname" $ }}-image-pull-secret-binder-registry"
type: kubernetes.io/dockerconfigjson
data:
  {{- $dockerconfig := (
    dict "auths" (
      dict .Values.binderhub.registry.url (
        dict "auth"
          (printf "%s:%s" .Values.binderhub.registry.username .Values.binderhub.registry.password | b64enc)
      )
    )
  ) }}
  .dockerconfigjson: {{ $dockerconfig | toJson | b64enc }}
---
{{- end }}
