{{- define "seaweedfs_s3_config" -}}
identities:
  - name: "{{ .Values.global.seaweedfs.catalogueBucket.bucket_name }}"
    credentials:
      - accessKey: "{{ .Values.global.secrets.seaweedfs.catalogueBucket.access_key }}"
        secretKey: "{{ .Values.global.secrets.seaweedfs.catalogueBucket.secret_key }}"
    actions:
      - "Read:{{ .Values.global.seaweedfs.catalogueBucket.bucket_name }}"
      - "Write:{{ .Values.global.seaweedfs.catalogueBucket.bucket_name }}"
      - "List:{{ .Values.global.seaweedfs.catalogueBucket.bucket_name }}"
  - name: "{{ .Values.global.seaweedfs.argoBucket.bucket_name }}"
    credentials:
      - accessKey: "{{ .Values.global.secrets.seaweedfs.argoBucket.access_key }}"
        secretKey: "{{ .Values.global.secrets.seaweedfs.argoBucket.secret_key }}"
    actions:
      - "Read:{{ .Values.global.seaweedfs.argoBucket.bucket_name }}"
      - "Write:{{ .Values.global.seaweedfs.argoBucket.bucket_name }}"
      - "List:{{ .Values.global.seaweedfs.argoBucket.bucket_name }}"
{{- end }}
{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.seaweedfs.s3.existingConfigSecret }}"
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
stringData:
  seaweedfs_s3_config: |
    {{- include "seaweedfs_s3_config" . | fromYaml | toJson | nindent 4 }}
{{- end }}
