{{- if index .Values "argo-workflows" "enabled" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "naavre.fullname" . }}-argo-s3-credentials
  labels:
    {{- include "naavre.labels" . | nindent 4 }}
data:
  accessKey: "{{ .Values.global.secrets.seaweedfs.argoBucket.access_key | default "" | b64enc }}"
  secretKey: "{{ .Values.global.secrets.seaweedfs.argoBucket.secret_key | default "" | b64enc }}"
{{- end }}