{{- if index .Values "argo-workflows" "enabled" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resubmitter
rules:
  # k8s standard APIs - minimal access for inspecting workflow pods/events
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - delete
  # Argo Workflows: allow creating (resubmitting) and reading workflows and templates
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
      - clusterworkflowtemplates
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resubmitters
subjects:
- kind: ServiceAccount
  name: resubmitter
roleRef:
  kind: Role
  name: resubmitter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resubmitter
  annotations:
    workflows.argoproj.io/rbac-rule: "'resubmitters' in groups"
    # This determines which RBAC rule should take precedence when multiple rules match.
    workflows.argoproj.io/rbac-rule-precedence: "3"
---
apiVersion: v1
kind: Secret
metadata:
  name: resubmitter.service-account-token
  annotations:
    kubernetes.io/service-account.name: resubmitter
type: kubernetes.io/service-account-token
{{- end }}

