import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('chrome-error://chromewebdata/');
  await page.getByRole('button', { name: 'Advanced' }).click();
  await page.getByRole('link', { name: 'Proceed to naavre-dev.' }).click();
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('user');
  await page.getByRole('textbox', { name: 'Username or email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('user');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'NaaVRE Open Lab image Sample' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Launch my instance' }).click();
  const page1 = await page1Promise;
  await page1.goto('https://naavre-dev.minikube.test/jupyter/user/user/lab/workspaces/openlab');
  await page1.getByRole('img', { name: 'Python [conda env:vanilla]' }).first().click();
  await page1.locator('.cm-line').first().click();
  await page1.getByRole('textbox').fill('# t1\n\n\na = 1');
  await page1.getByRole('textbox').press('ControlOrMeta+s');
  await page1.getByRole('button', { name: 'Rename' }).click();
  await page1.getByLabel('notebook content').getByRole('button', { name: 'Insert a cell below (B)' }).click();
  await page1.locator('.lm-Widget.jp-CodeMirrorEditor.jp-Editor.jp-InputArea-editor.jp-mod-at-line-beginning > .cm-editor > .cm-scroller > .cm-content > .cm-line').click();
  await page1.getByRole('textbox').filter({ hasText: /^$/ }).fill('# t2\n\n\nb = a + 1');
  await page1.getByRole('textbox').filter({ hasText: /^$/ }).press('ControlOrMeta+s');
  await page1.locator('.lm-Widget.jp-CodeMirrorEditor.jp-Editor.jp-InputArea-editor.jp-mod-at-line-beginning > .cm-editor > .cm-scroller > .cm-content > .cm-line').click();
  await page1.getByRole('option', { name: 'python' }).click();
  await page1.getByRole('button', { name: 'Containerize' }).click();
  await page1.getByText('Containerizing t2-user:').click();
});