nameOverride: ""
fullnameOverride: ""

argo-workflows:
  enabled: true

jupyterhub:
  enabled: true

k8s-secret-creator:
  enabled: true

keycloak:
  enabled: true
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/keycloak
  keycloakConfigCli:
    image:
      repository: bitnamilegacy/keycloak-config-cli
  postgresql:
    image:
      repository: bitnamilegacy/postgresql
    volumePermissions:
      image:
        repository: bitnamilegacy/bitnami-shell
    metrics:
      image:
        repository: bitnamilegacy/postgres-exporter

naavre-catalogue-service:
  enabled: true

naavre-containerizer-service:
  enabled: true

naavre-workflow-service:
  enabled: true

naavre-paas-frontend:
  enabled: true

global:
  ingress:
    redirectDomainToPaasFrontend: false

  secrets:
    keycloak:
      client_id:
      client_secret:

  vlabLabels:
    sampleLabel:
      title: Sample Label
      color: "#3c8f49"

  vlabs:
    openlab:
      enabled: true
      slug: openlab
      title: "NaaVRE Open Lab"
      labels: [sampleLabel]
      description: "Open experimentation with virtual labs"
      dirname: "Open Lab"
      icon: ""
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-vanilla-jupyter
        tag: v0.0.1
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.0.1/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url:
        cell_github_token:
        registry_url:
        git_public: {}
