nameOverride: ""
fullnameOverride: ""

argo-workflows:
  enabled: true

jupyterhub:
  enabled: true

k8s-secret-creator:
  enabled: true

keycloak-db:
  enabled: true

naavre-catalogue-service:
  enabled: true

naavre-containerizer-service:
  enabled: true

naavre-workflow-service:
  enabled: true

naavre-paas-frontend:
  enabled: true

global:
  ingress:
    domain: example.com
    commonAnnotations: {}
    redirectDomainToPaasFrontend: false
    basePaths:
      keycloak: /auth

  secrets:
    keycloak:
      client_id:
      client_secret:
      adminPassword:
      users: []
      # users:
      #   - username: example-1
      #     password: ...
      postgresql:
        database:
        username:
        password:

  communities: {}
  # myCommunity:
  #   title: My community

  vlabLabels: {}
  # myLabel:
  #   title: My label
  #   color: "#3c8f49"


  vlabs:
    openlab:
      enabled: true
      slug: openlab
      title: "NaaVRE Open Lab"
      communities: []
      # communities: [myCommunity]
      labels: []
      # labels: [myLabel]
      description: "Open experimentation with virtual labs"
      dirname: "Open Lab"
      icon: ""
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-vanilla-jupyter
        tag: v0.0.1
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.0.1/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url:
        cell_github_token:
        registry_url:
        git_public: {}
