name: Deploy to k8s-staging-1

on:
  release:
    types: [published]

jobs:
  deploy-staging:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: deploy/k8s-staging-1
    secrets: inherit
