name: Deploy NaaVRE

on:
  push:
    branches:
      - deploy/k8s-test-1

env:
  SOPS_VERSION: v3.12.2

permissions:
  id-token: write

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::050752621342:role/github-actions-naavre-helm-deploy
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-3

      - name: Install sops
        run: |
          wget https://github.com/mozilla/sops/releases/download/${{ env.SOPS_VERSION }}/sops-${{ env.SOPS_VERSION }}.linux.amd64
          chmod +x sops-${{ env.SOPS_VERSION }}.linux.amd64
          sudo mv sops-${{ env.SOPS_VERSION }}.linux.amd64 /usr/local/bin/sops

      - name: Test sops
        run: |
          sops decrypt ./hello.yaml
