name: Deploy NaaVRE

on:
  push:
    branches:
      - deploy/k8s-test-1

env:
  SOPS_VERSION: v3.12.2

permissions:
  id-token: write

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: deploy/k8s-test-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::050752621342:role/github-actions-naavre-helm-deploy
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-3

      - name: Install sops
        run: |
          wget https://github.com/mozilla/sops/releases/download/${{ env.SOPS_VERSION }}/sops-${{ env.SOPS_VERSION }}.linux.amd64
          chmod +x sops-${{ env.SOPS_VERSION }}.linux.amd64
          sudo mv sops-${{ env.SOPS_VERSION }}.linux.amd64 /usr/local/bin/sops

      - name: Test sops
        run: |
          sops decrypt ./hello.yaml

      - name: Open SSH tunnel
        run: |
          TUNNEL_LOCAL_ADDRESS=127.0.0.1
          TUNNEL_PORT=6443
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ vars.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          cmd="ssh -fNL $TUNNEL_LOCAL_ADDRESS:$TUNNEL_PORT:localhost:$TUNNEL_PORT ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}"
          echo "running: $cmd"
          $cmd
          echo "done"
          echo "sleeping"
          sleep 2
          echo "done"
          echo "getting pid"
          SSH_TUNNEL_PID=$(pgrep -f "$cmd")
          echo "done"
          echo "SSH_TUNNEL_PID=$SSH_TUNNEL_PID" >> $GITHUB_ENV
          echo "$TUNNEL_LOCAL_ADDRESS ${{ vars.KUBE_CONTEXT }}" | sudo tee -a /etc/hosts

      - name: Setup Kubeconfig
        run: |
          mkdir -p ~/.kube
          chmod 700 ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Test kubectl
        run: |
          kubectl --context ${{ vars.KUBE_CONTEXT }} get no

      - name: Test helm
        run: |
          helm --kube-context ${{ vars.KUBE_CONTEXT }} -n new-naavre list

      - name: Close SSH tunnel
        if: always()
        shell: bash
        run: |
          if [ ! -z "$SSH_TUNNEL_PID" ]; then
            kill $SSH_TUNNEL_PID 2>/dev/null || true
          fi
