name: Lint helm values

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'

jobs:
  validate-images:
    name: Lint helm values
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Jupyter Lab image manifests
        run: |
          set -euo pipefail

          VALUES_DIR="values"

          run_cmd() {
            cmd="$1"
            echo "$cmd"
            bash -c "$cmd"
          }

          ./deploy.sh repo-add
          ./deploy.sh dependency-build

          # Paired values-{public,secrets}.yaml files
          find "${VALUES_DIR}" -maxdepth 1 -name "values-*.public.yaml" \
          | while read -r public_file; do
            secrets_file="${public_file%.public.yaml}.secrets.yaml"
            if [[ ! -f "$secrets_file" ]]; then
              echo "Public file has no matching secrets file:"
              echo "  public file: $public_file"
              echo "  missing secrets file: $secrets_file"
              echo "Create file $secrets_file, or rename $public_file to ${public_file%.public.yaml}.yaml"
              exit 1
            fi
            echo "--- Linting values: $public_file $secrets_file"
            run_cmd "./deploy.sh --no-dependency-build --include-labs -f \"$secrets_file\" -f \"$public_file\" lint"
          done

          # Standalone files
          find "${VALUES_DIR}" -maxdepth 1 -name "values-*.yaml" ! -name "*.public.yaml" ! -name "*.secrets.yaml" \
          | while read -r values_file; do
            echo "--- Linting values: $values_file"
            run_cmd "./deploy.sh --no-dependency-build -f \"$values_file\" lint"
          done
