name: test-minikube-script
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 4 5,25 * *'


jobs:
  test-minikube-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - scripts/argo-workflows-0.45.6-Chart.yaml
          - scripts/argo-workflows-0.33.1-Chart.yaml
    steps:
      - uses: actions/checkout@v4

      - name: start Minikube
        id: minikube
        uses: medyagh/setup-minikube@v0.0.19
        with:
          addons: ingress,ingress-dns

      - name: Try the cluster
        run: kubectl get pods -A

      - name: Run setup-tests.sh
        shell: bash -l {0}
        run: |
          chmod +x ./scripts/setup-tests.sh 
          ./scripts/setup-tests.sh -f values/values-deploy-minikube.yaml -d -n -u -p -v -c "${{ matrix.chart }}"

      - name: Test auth token with python jwt library
        run: |
          pip install pyjwt
          python -c "import jwt; import os; token = os.getenv('AUTH_TOKEN'); decoded = jwt.decode(token, options={'verify_signature': False}); print(decoded)"

      - name: Run playwright tests
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: |
          cd tests
          npm ci

      - name: Install Playwright Browsers
        run: |
          cd tests
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd tests
          npx playwright test